### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by janrop** [jeboehm/docker-shopware#1]
Hey there,

first up thanks for the great work.
Unfortunately the product images are not loading for the dome articles. Is that normal?

Thanks

**Comment by jeboehm** [comment]
Hi,

thanks for using!
This is a known issue, they are not shipped within the Shopware downloads.

I will try to fix it soon.

**Comment by kaptankorkut** [comment]
Solved here: [https://github.com/jeboehm/docker-shopware/issues/7#issuecomment-346699515](url)
