### ISSUE TITLE
Sometime requests in backend fails

### ISSUE THREAD

**Issue by shyim** [jeboehm/docker-shopware#2]
I get very often when i load the backend the error "Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING on request http://sw52.dev/backend/base?file=bootstrap&___REVISION___".

After a reload it works. And after 5-6 reloads it comes back -,-.
Have you a idea?

**Comment by jeboehm** [comment]
Hi @shyim,
are there some errors in the log output of the shopware container?

**Comment by shyim** [comment]
2017/03/03 21:46:59 [crit] 10#0: *35 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 192.168.0.24, server: ~^(www\.)?(?<sname>.+?).dev$, request: "GET /backend/base?file=bootstrap&___REVISION___ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "sw52.dev", referrer: "http://sw52.dev/backend/"
192.168.0.24 - - [03/Mar/2017:21:46:59 +0000] "GET /backend/base?file=bootstrap&___REVISION___ HTTP/1.1" 200 405563 "http://sw52.dev/backend/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Comment by shyim** [comment]
There also permission issues on uploading images
 [crit] 11#0: *5 open() "/var/lib/nginx/tmp/client_body/0000000001" failed (13: Permission denied)

**Comment by jeboehm** [comment]
Hi @shyim 
I've merged https://github.com/jeboehm/docker-php-nginx-base/pull/1 and added Shopware version 5.2.20. The new version is based on the new php-nginx-base image.
Would you like to try it again?

**Comment by shyim** [comment]
It looks like fixed. Thanks

**Comment by jeboehm** [comment]
Yay! Thanks for your help :)
