### ISSUE TITLE
Cronjob error: Could not connect to database

### ISSUE THREAD

**Issue by patricklenz** [jeboehm/docker-shopware#3]
Im trying to run `./bin/console sw:theme:dump:configuration`. Unfortunately Im getting the following errors:

`WARNING! Could not connect to database. Message from SQL Server: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /path/to/installation/myshop/shopware/engine/Shopware/Components/DependencyInjection/Bridge/Db.php`

`[Symfony\Component\DependencyInjection\Exception\RuntimeException]
  You have requested a synthetic service ("db_connection"). The DIC does not
  know how to construct this service.`

**Comment by jeboehm** [comment]
Hi @patricklenz ,
I suppose that you don't run the command in the Docker container itself.
To do this, you have to run `docker-compose exec shopware sh` at first.

Maybe this helps?

**Comment by patricklenz** [comment]
That works! Great, thank you!
