### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by dciccale** [jeboehm/docker-shopware#4]
Just trying this out, and the first time I run `docker-compose up` I went to `http://127.0.0.1:8080` and got this message "503 Service Unavailable"

These are the logs from docker-compose:
```
percona_1   | 2017-06-02T09:35:42.520488Z 11 [Note] Access denied for user 'swuser'@'172.18.0.3' (using password: YES)
shopware_1  | 127.0.0.1 -  02/Jun/2017:09:35:42 +0000 "GET /shopware.php" 500
shopware_1  | 172.18.0.1 - - [02/Jun/2017:09:35:42 +0000] "GET / HTTP/1.1" 503 34 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
```

What could this be and how could I fix it?

Thanks in advance

**Comment by jeboehm** [comment]
Hi,
it seems that you're using the wrong configuration file. Delete your config.php and restart the containers.

**Comment by dciccale** [comment]
Yes that worked! thanks

**Comment by jeboehm** [comment]
Great! :)

**Comment by Isengo1989** [comment]
Hi Jeffrey,
I got an similar Error:

> shopware_1  | 127.0.0.1 -  19/Aug/2017:13:42:59 +0000 "GET /shopware.php" 503
> shopware_1  | 172.18.0.1 - - [19/Aug/2017:13:42:59 +0000] "GET / HTTP/1.1" 503 213 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"


Deleting the config.php and using docker-compose down and up again did not work. Any ideas?
