### ISSUE TITLE
Cache is not writable

### ISSUE THREAD

**Issue by uuf6429** [jeboehm/docker-shopware#5]
I'm not sure what is the reason, however when I run this (via `docker toolbox` and no volume for `/var/www/html`), the site fails to load due to not being able to write to `/var/www/html/web/cache/`.

I got it it working by adding the cache directory, mentioned above, at the end of the [chmod line in the entrypoint script](https://github.com/jeboehm/docker-shopware/blob/master/rootfs/usr/local/bin/entrypoint.sh#L25).

My hacky & ugly solution, (hopefully short-term), was to bundle a copy of the entrypoint script and make docker overwrite the default one with it.

Would be pretty great to see this fixed in all docker tags.

**Edit:** Later on I have the same issue when uploading plugins; I get an error that `/var/www/html/files/downloads/` is not writable.

**Comment by jeboehm** [comment]
Thank you for your feedback!
