### ISSUE TITLE
No Images after Container is up and running

### ISSUE THREAD

**Issue by naps164** [jeboehm/docker-shopware#7]
After successfully starting the Container, there are no Images shown in the Frontend? Did I do something wrong?

**Comment by kaptankorkut** [comment]
The unpacked images are placed directly into images folder. Shopware 5.1 includes a new media management layer, which abstracts the location of your media files like /media/image/0a/20/03/my-fancy-image.png. Having unpacked the images in a plain directory structure you need to configure a media adapter to tell Shopware where to find those. Adding following snippet to your config.php
solves the problem first.

```
'cdn' => [
    'adapters' => [
        'local' => [
            'type' => 'local',
            'mediaUrl' => '',
            'strategy' => 'plain',
            'path' => realpath(__DIR__ . '/')
        ]
    ]
]  
```

However it's highly recommended to migrate the images to the abstract directory structure. You can find more information here: https://developers.shopware.com/developers-guide/shopware-5-media-service/#example:-migrating-back-to-the-simple-directory-structure

**Comment by jeboehm** [comment]
Hey, thanks for your feedback. You can find instructions for solving this problem in the updated README.
