### ISSUE TITLE
Standart Zugangsdaten fürs Backend

### ISSUE THREAD

**Issue by gruselhaus** [jeboehm/docker-shopware#9]
Moin,

wie lauten die Standard Zugangsdaten fürs Backend?

Nico

CC @ilvani

**Comment by jeboehm** [comment]
Hallo @gruselhaus ,
ich bin mir gerade nicht ganz sicher, aber admin / demo, demo / demo oder admin / admin sollte funktionieren.

Jeff

**Comment by gruselhaus** [comment]
Hi,

danke für die schnelle Antwort.

demo/demo stimmt.

Merci!

**Comment by jeboehm** [comment]
Nice, das freut mich.
Wenn du Lust hast, hinterlässt mir gerne einen PR für die README.md mit den Zugangsdaten. :)
